---
title: "Produktionsmanagement"
subtitle: "Universität Duisburg-Essen - Wintersemester 2025/2026"
---

## Einleitung

Dieser Kurs behandelt das Modul Produktionsmanagement auf Basis der ursprünglichen Vorlesung von Prof. Dr. Manitz. Ich habe den Kurs kurzfristig übernommen und die Materialien deswegen lediglich leicht angepasst. Es sind keine neuen Inhalte enthalten, sondern lediglich angepasste Übungen.

## Online Meetings

Wie besprochen, finden vor der Prüfung noch 3 Online-Meetings zur Klärung Ihrer Fragen statt. Die Daten der Meetings sind wie folgt:

- 20.10.2025, um 14:15 Uhr
- 22.10.2025, um 08:15 Uhr
- 01.12.2025, um 12:15 Uhr

Alle Meetings können Sie [über diesen Link erreichen.](https://meet.google.com/ant-hrew-xtf)

## Lernziele

Mein Ziel ist es, Ihnen einige wichtige Grundlagen in der Produktion näherzubringen. Diese Konzepte werden sowohl in der Wissenschaft als auch in der Industrie eingesetzt und sind gute Werkzeuge für die Praxis.

Nach Abschluss dieses Kurses werden Sie in der Lage sein:

- Standortplanung mit und ohne Kapazitätsbeschränkungen durchzuführen
- Leistungsanalyse und grundlegende Warteschlangenmodelle zu erstellen
- Grundlagen im Qualitätsmanagement anzuwenden
- Kernkonzepte der Ressourcen und Produktionsprogrammplanung zu verstehen

Es sind keine fortgeschrittenen Kenntnisse oder Erfahrungen erforderlich, um den Inhalten zu folgen, obwohl Grundkenntnisse in statistischen Methoden, Operations Research und Mathematik hilfreich sind. Ferner entsprechen nicht alle Inhalte der Vorlesung dem jeweils letzten Stand der Forschung, da die Folien von Prof. Dr. Manitz stammen und teils etwas älter sind.

## Kursabschnitte

Der Kerninhalt des Kurses ist in sechs Abschnitte gegliedert:

1. **Grundlagen & Standortplanung**
2. **Fließbandproduktion & Leistungsanalysen**
3. **Zentrenproduktion & Qualitätsmanagement**
4. **Produktionsprogrammplanung**
5. **Ressourceneinsatzplanung & Losgrößen**
6. **Wiederholung und offene Fragen**

## Tutorials

Die Tutorials sind von mir auf Basis der Vorlesung von Prof. Dr. Manitz erstellt worden. Sie helfen Ihnen, die Konzepte aus der Vorlesung anzuwenden und zu verstehen. Die Klausur am Ende orientiert sich an den Probeklausuren von Herrn Manitz und wird die Themen der Vorlesung abdecken, die wir gemeinsam behandelt haben.

## Fragen und Unterstützung

Für Ihre Fragen stehe ich jederzeit gerne zur Verfügung. Kontaktieren Sie mich einfach per E-Mail unter [tobias.vlcek@uni-due.de](mailto:tobias.vlcek@uni-due.de?subject=Produktionsmanagement%3A%20%3CIhr%20Betreff%3E).

Zusätzlich steht Ihnen auf dieser Seite ein Chatbot zur Verfügung, der auf den Inhalten der Vorlesung basiert und Ihnen bei inhaltlichen Fragen unterstützend zur Seite stehen kann. Er ist nicht perfekt und eher eine Beta-Version, aber ich hoffe, dass er Ihnen dennoch hilft.
