---
title: "Häufig gestellte Fragen"
subtitle: "Antworten auf gängige Fragen"
---

## Unbeantwortete Fragen

Falls Sie eine Frage haben, die hier nicht beantwortet wird, teilen Sie mir dies bitte mit, indem Sie mir eine E-Mail an [tobias.vlcek@uni-due.de](mailto:tobias.vlcek@uni-due.de?subject=Produktionsmanagement%3A%20%3CIhr%20Betreff%3E). Sollten Sie einen Fehler im Kursmaterial gefunden haben oder Vorschläge zur Verbesserung des Kurses haben, teilen Sie mir dies bitte ebenfalls sehr gerne mit!

## FAQs

### Kann ich die Übungen auch als PDF herunterladen?

Ja, die Übungen können als PDF herunterladen werden. Die Datei finden Sie auf der jeweiligen Seite der Übung, wenn Sie auf "PDF" klicken.

### Woran orientiert sich die Klausur?

Die Klausur orientiert sich primär an den Probeklausuren von Herrn Manitz und wird die Themen der Vorlesung abdecken, die wir gemeinsam behandelt haben. Wenn ihr die von uns behandelten Themen der alten Klausuren rechnen könnt und die Übungen verstanden habt, seid ihr sehr gut vorbereitet.

### Wie ist die Klausur aufgebaut?

**Die Klausur wird aus etwa 4-5 Teilen bestehen, die alle bearbeitet werden müssen.**
Um einen Überblick von dem Klausurformat zu bekommen, mit dem ich in der Regel arbeite, schauen Sie sich gerne die Klausur zu [Produktionswirtschaft II](pw2-2025.pdf) und [Materiallogistik](mlb-2025.pdf) aus dem Frühjahr 2025 an.

### Wie lange dauert die Klausur?

Die Klausur hat eine Länge von 60 Minuten.

### Wie ist die Klausur aufgebaut?

Die Klausur besteht aus 5 Aufgaben und ss sind **vier von fünf** Aufgaben zu bearbeiten (je 15 Punkte pro Aufgabe, max. 60 Punkte).

:::{.callout-warning}
Die bearbeiteten Aufgaben, die gewertet werden sollen, sind kenntlich zu machen. Ansonsten werden die Lösungen grundsätzlich in der Reihenfolge der Aufgaben in der Klausur bewertet!
:::

### Welche Themen sind ausgeschlossen?

Alles, was in den Vorlesungsfolien und Übungen auf der Website behandelt wird, kann in der Prüfung vorkommen. Themen aus Altklausuren, die weder in den Folien noch in den Übungen enthalten sind, werden nicht abgefragt.

### Kann es auch sein, dass in der Klausur ein Modell formuliert werden muss?

Ja, es kann gut sein, dass in der Klausur ein Modell formuliert werden muss.

### Bekomme ich bezüglich meiner Note früher Bescheid, wenn ich im dritten Versuch bin?

Nein, alle Noten werden gleichzeitig veröffentlicht.
